package com.learning.proveedoresapp.model

import com.google.gson.annotations.SerializedName
import java.util.Date

data class Proveedor(
    val id: Int,
    val empresa: String,
    @SerializedName("id_solicitante") val idSolicitante: Int,
    @SerializedName("nombre_solicitante") val nombreSolicitante: String,
    @SerializedName("fecha_creacion") val fechaCreacion: String,
    @SerializedName("id_modificador") val idModificador: Int,
    @SerializedName("nombre_modificador") val nombreModificador: String,
    @SerializedName("fecha_modificacion") val fechaModificacion: String,
    @SerializedName("tipo_alta") val tipoAlta: String,
    val persona: String,
    @SerializedName("razon_social") val razonSocial:String,
    val rfc: String,
    val curp: String,
    @SerializedName("regimen_capital") val regimenCapital: String,
    @SerializedName("nombre_fiscal") val nombreFiscal: String,
    @SerializedName("nombre_comercial") val nombreComercial: String,
    @SerializedName("uso_cfdi") val usoCFDI: String,
    @SerializedName("representante_legal") val representanteLegal: String,
    @SerializedName("telefono_1") val telefono1: String,
    @SerializedName("telefono_2") val telefono2: String,
    val contacto: String,
    val grupo: String,
    @SerializedName("correo_general") val correoGeneral: String,
    @SerializedName("correo_pagos") val correoPagos: String,
    @SerializedName("sitio_web") val sitioWeb: String,
    val rubro: String,
    @SerializedName("tipo_operacion") val tipoOperacion: String,
    @SerializedName("tipo_tercero") val tipoTercero: String,
    @SerializedName("id_fiscal") val idFiscal: String,
    @SerializedName("regimen_fiscal") val regimenFiscal: String,
    @SerializedName("agente_aduanal") val agenteAduanal: String,
    @SerializedName("reg_inc_fiscal") val regIncFiscal: String,
    @SerializedName("impuesto_cedular") val impuestoCedular: String,
    @SerializedName("venc_s_fecha") val vencFecha: String,
    @SerializedName("dias_entrega_completa") val diasEntregaCompleta: Int,
    @SerializedName("dias_credito") val diasCredito: Int,
    @SerializedName("limite_credito_MN") val limiteCreditoMN: Double,
    @SerializedName("limite_credito_ME") val limiteCreditoME: Double,
    @SerializedName("monto_credito") val montoCredito: Double,
    @SerializedName("retencion_iva") val retencionIVA: String,
    @SerializedName("retencion_isr") val retencionISR: String,
    @SerializedName("iva_frontera") val ivaFrontera: String,
    val calle: String,
    @SerializedName("numero_exterior") val numeroExterior: String,
    @SerializedName("numero_interior") val numeroInterior: String,
    @SerializedName("codigo_postal") val codigoPostal: String,
    val colonia: String,
    val localidad: String,
    val municipio: String,
    val estado: String,
    val pais: String,
    val banco: String,
    val cuenta: String,
    val moneda: String,
    val clabe: String,
    @SerializedName("banco_2") val banco2: String,
    @SerializedName("cuenta_2") val cuenta2: String,
    @SerializedName("moneda_2") val moneda2: String,
    @SerializedName("clabe_2") val clabe2: String,
    @SerializedName("nombre_constancia") val nombreConstancia: String,
    @SerializedName("ruta_constancia") val rutaConstancia: String,
    @SerializedName("nombre_estado_cuenta") val nombreEstadoCuenta: String,
    @SerializedName("ruta_estado_cuenta") val rutaEstadoCuenta: String,
    @SerializedName("usar_portal_prov") val usarPortalProv: Boolean,
    @SerializedName("no_aplica_rafaga") val noAplicaRafaga: Boolean,
    @SerializedName("no_relacionar_oc") val noRelacionarOC: Boolean,
    val folio: String,
    val compras: Boolean,
    val finanzas: Boolean,
    val sistemas: Boolean,
    val aprobado: Boolean,
    @SerializedName("rechazado_compras") val rechazadoCompras: Boolean,
    @SerializedName("rechazado_finanzas") val rechazadoFinanzas: Boolean,
    @SerializedName("rechazado_sistemas") val rechazadoSistemas: Boolean,
    val comentarios: String
) {

}